name: DevRook-FE pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing Node Modules
      run: |
        npm cache clean --force
        rm -rf node_modules
        npm i

    - name: Code Format Checking
      run: npm run formatCheck
    
    - name: Deploing GitHub Pages
      # If its not setted to true then it will treat warnings as error
      env:
       CI: false
      run: |
        git config --global user.email ${{ secrets.GH_EMAIL }}
        git config --global user.name ${{ secrets.GH_USERNAME }}
        git remote set-url origin https://${{ secrets.GH_PERSONAL_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/devrook-FE.git
        npm run deploy
