name: DevRook-FE pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing Node Modules
      run: npm i

    - name: Code Format Checking
      run: npm run formatCheck
    
    - name: Running Predeploy
      run: npm run predeploy

    - name: Deploing GitHub Pages
      run: |
        npm run deploy
